### ISSUE TITLE
Unable to start after fresh install

### ISSUE THREAD

**Issue by JasonTheAdams** [xybu/onedrive-d-old#52]
I'm on Ubuntu x64. I downloaded and installed, and immediately got the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PyYAML
```

The same error occurs if I run onedrive-d, any ideas?

**Comment by JasonTheAdams** [comment]
I just noticed this in the installation:

```
Installed /usr/local/lib/python2.7/dist-packages/notify2-0.3-py2.7.egg
Searching for PyYAML
Reading https://pypi.python.org/simple/PyYAML/
Best match: PyYAML 3.11
Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.zip#md5=89cbc92cda979042533b640b76e6e055
Processing PyYAML-3.11.zip
Writing /tmp/easy_install-3m8b6t/PyYAML-3.11/setup.cfg
Running PyYAML-3.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3m8b6t/PyYAML-3.11/egg-dist-tmp-Aqg5YS
ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
 #include "pyconfig.h"

compilation terminated
```

**Comment by kleberpna** [comment]
I got exactly the same error when executing the onedrive-d binary:

[kleber@ultra ~]$ onedrive-d
Traceback (most recent call last):
  File "/usr/bin/onedrive-d", line 9, in <module>
    load_entry_point('onedrive-d==0.85', 'console_scripts', 'onedrive-d')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg/onedrive_d/daemon.py", line 8, in <module>
    import components
  File "/usr/lib/python2.6/site-packages/onedrive_d-0.85-py2.6.egg/onedrive_d/components.py", line 17, in <module>
    from onedrive import api_v5
  File "/usr/lib/python2.6/site-packages/onedrive/api_v5.py", line 500
    type_filter = {type_filter}
                              ^
SyntaxError: invalid syntax

**Comment by kleberpna** [comment]
And durring the installation, I noticed one compilation error:

Downloading https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.zip#md5=89cbc92cda979042533b640b76e6e055
Processing PyYAML-3.11.zip
Running PyYAML-3.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6J1XLg/PyYAML-3.11/egg-dist-tmp-BjZtAQ
build/temp.linux-x86_64-2.6/check_libyaml.c:2:18: error: yaml.h: Arquivo ou diretório não encontrado
build/temp.linux-x86_64-2.6/check_libyaml.c: In function ‘main’:
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: ‘yaml_parser_t’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: (Each undeclared identifier is reported only once
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: for each function it appears in.)
build/temp.linux-x86_64-2.6/check_libyaml.c:5: error: expected ‘;’ before ‘parser’
build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: ‘yaml_emitter_t’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:6: error: expected ‘;’ before ‘emitter’
build/temp.linux-x86_64-2.6/check_libyaml.c:8: warning: implicit declaration of function ‘yaml_parser_initialize’
build/temp.linux-x86_64-2.6/check_libyaml.c:8: error: ‘parser’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:9: warning: implicit declaration of function ‘yaml_parser_delete’
build/temp.linux-x86_64-2.6/check_libyaml.c:11: warning: implicit declaration of function ‘yaml_emitter_initialize’
build/temp.linux-x86_64-2.6/check_libyaml.c:11: error: ‘emitter’ undeclared (first use in this function)
build/temp.linux-x86_64-2.6/check_libyaml.c:12: warning: implicit declaration of function ‘yaml_emitter_delete’

libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
zip_safe flag not set; analyzing archive contents...
Adding PyYAML 3.11 to easy-install.pth file

**Comment by vishalkrv** [comment]
Even I'm facing the same issue. Any Fix?

**Comment by xybu** [comment]
PyYAML is a required package for mk-fg/python-onedrive. And looks like it doesn't work on Python2.6.
May you update to Python2.7+, or try out the 1.0-dev version of onedrive-d (requiring Py3k+ but no PyYAML)?

**Comment by vishalkrv** [comment]
Okay, I installed the latest version(1.0). However when I try to run onedrive-d command or onedrive-pref command, it gives me a error saying command not found.  what should I do ?

**Comment by xybu** [comment]
Since it is a very early version, I don't have it hooked to the system.

To run the program,
cd onedrive_d
./prefs.py --help
./daemon.py --help

Sorry I forgot the actual cmd args... --no-gui or something. Please have a look at the source.

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by Dutchglory** [comment]
note: on linux onedrive-d executables are installed at /opt/local/...
after you run initial setup(s)  and installed dependencies ...

**Comment by xybu** [comment]
I am sorry, but which Linux distro are you using? I assume all users run this program "on linux"...

**Comment by vishalkrv** [comment]
Hi,
I'm running Ubuntu 14.04. Here is the output on running the installation:

Reading package lists... Done
Building dependency tree  
Reading state information... Done
git is already the newest version.
inotify-tools is already the newest version.
python3-pip is already the newest version.
python3-gi is already the newest version.
The following packages were automatically installed and are no longer required:
  kde-l10n-engb kwalletmanager libmodemmanagerqt1 libnetworkmanagerqt1
  liboath0 libopenconnect2
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating onedrive_d.egg-info
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing onedrive_d.egg-info/PKG-INFO
writing requirements to onedrive_d.egg-info/requires.txt
writing top-level names to onedrive_d.egg-info/top_level.txt
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/onedrive_d
copying onedrive_d/pref.py -> build/lib/onedrive_d
copying onedrive_d/observer_gtk.py -> build/lib/onedrive_d
copying onedrive_d/observer_dummy.py -> build/lib/onedrive_d
copying onedrive_d/logger.py -> build/lib/onedrive_d
copying onedrive_d/pref_gtk.py -> build/lib/onedrive_d
copying onedrive_d/setup.py -> build/lib/onedrive_d
copying onedrive_d/live_api.py -> build/lib/onedrive_d
copying onedrive_d/main.py -> build/lib/onedrive_d
copying onedrive_d/test_live_api.py -> build/lib/onedrive_d
copying onedrive_d/daemon.py -> build/lib/onedrive_d
copying onedrive_d/pref_cmd.py -> build/lib/onedrive_d
copying onedrive_d/**init**.py -> build/lib/onedrive_d
copying onedrive_d/config.py -> build/lib/onedrive_d
creating build/lib/onedrive_d/res
copying onedrive_d/res/icon_256.png -> build/lib/onedrive_d/res
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/observer_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/observer_dummy.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/logger.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_gtk.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/setup.py -> build/bdist.linux-x86_64/egg/onedrive_d
creating build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/res/icon_256.png -> build/bdist.linux-x86_64/egg/onedrive_d/res
copying build/lib/onedrive_d/live_api.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/main.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/test_live_api.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/daemon.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/pref_cmd.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/**init**.py -> build/bdist.linux-x86_64/egg/onedrive_d
copying build/lib/onedrive_d/config.py -> build/bdist.linux-x86_64/egg/onedrive_d
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref.py to pref.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/observer_gtk.py to observer_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/observer_dummy.py to observer_dummy.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/logger.py to logger.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_gtk.py to pref_gtk.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/setup.py to setup.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/live_api.py to live_api.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/main.py to main.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/test_live_api.py to test_live_api.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/daemon.py to daemon.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/pref_cmd.py to pref_cmd.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/config.py to config.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
onedrive_d.**pycache**.observer_gtk.cpython-34: module references **file**
onedrive_d.**pycache**.setup.cpython-34: module references **file**
creating dist
creating 'dist/onedrive_d-1.0_dev-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing onedrive_d-1.0_dev-py3.4.egg
removing '/usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg' (and everything under it)
creating /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg
Extracting onedrive_d-1.0_dev-py3.4.egg to /usr/local/lib/python3.4/dist-packages
onedrive-d 1.0-dev is already the active version in easy-install.pth

Installed /usr/local/lib/python3.4/dist-packages/onedrive_d-1.0_dev-py3.4.egg
Processing dependencies for onedrive-d==1.0-dev
Searching for Send2Trash==1.3.0
Best match: Send2Trash 1.3.0
Processing Send2Trash-1.3.0-py3.4.egg
Send2Trash 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/Send2Trash-1.3.0-py3.4.egg
Searching for certifi==14.05.14
Best match: certifi 14.05.14
Processing certifi-14.05.14-py3.4.egg
certifi 14.05.14 is already the active version in easy-install.pth

Using /usr/local/lib/python3.4/dist-packages/certifi-14.05.14-py3.4.egg
Searching for urllib3==1.7.1
Best match: urllib3 1.7.1
urllib3 1.7.1 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Searching for requests==2.2.1
Best match: requests 2.2.1
requests 2.2.1 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for onedrive-d==1.0-dev
running clean

Please issue command 'onedrive-pref [--no-gui]' to configure the app,
and then issue command 'onedrive-d [--no-gui]' to start the daemon.
All operations finished.

**Comment by sanchomuzax** [comment]
Similar problem on Lubuntu 14.10 with 1.0-dev:

$ onedrive-d
Traceback (most recent call last):
  File "/usr/local/bin/onedrive-d", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: onedrive-d==0.85

**Comment by xybu** [comment]
Could you try out 1.0-dev?

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by sanchomuzax** [comment]
Yes, i tried the 1.0-dev.
2014.10.27. 22:33 ezt írta ("Xiangyu Bu" notifications@github.com):

**Comment by xybu** [comment]
I see the problem. Since 1.0-dev does not hook itself with the system at this stage, the command onedrive-d is not registered. You could run by executing the script
onedrive_d/main.py
onedrive_d/pref.py --no-gui

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by sanchomuzax** [comment]
It's running. But not too fine... And I can't access the gui.

2014-10-27 22:46 GMT+01:00 Xiangyu Bu notifications@github.com:

**Comment by xybu** [comment]
No GUI at this stage yet :(

Sincerely,
Xiangyu Bu

Sent from my Windows Phone

**Comment by sanchomuzax** [comment]
Ok, I understand it. How can I sync only the preferred subfolders from
OneDrive? I don't wan't to sync all folders to my PC.
2014.10.27. 23:16 ezt írta ("Xiangyu Bu" notifications@github.com):

**Comment by xybu** [comment]
Probably add the files / folders you want to ignore to ~/.onedrive/ignore_list.txt (or something with similar file name, I forgot...)?

Sincerely,Xiangyu Bu

Date: Mon, 27 Oct 2014 15:29:15 -0700

**Comment by sanchomuzax** [comment]
Sorry, but I don't want to use text config for it, because high potential
for error, as with a gui.
I'm waiting for gui again.

2014-10-27 23:32 GMT+01:00 Xiangyu Bu notifications@github.com:
